<?php

return [
    'rows' => [
        [
            'id' => 'C1',
            'route_name' => 'insecure.documents.show',
            'resource' => 'Documents',
            'action' => 'Read',
            'object_reference' => 'ID',
            'rule_enforcement_point' => 'No policy or gate',
            'reviewed' => false,
            'evidence_notes' => 'Fails ownership enforcement; non-owner can read documents.',
        ],
        [
            'id' => 'C2',
            'route_name' => 'secure.documents.show',
            'resource' => 'Documents',
            'action' => 'Read',
            'object_reference' => 'ID',
            'rule_enforcement_point' => 'DocumentPolicy@view',
            'reviewed' => true,
            'evidence_notes' => 'Ownership enforced through policy authorization.',
        ],
        [
            'id' => 'C3',
            'route_name' => 'insecure.uuid.show',
            'resource' => 'Documents',
            'action' => 'Read',
            'object_reference' => 'UUID',
            'rule_enforcement_point' => 'UUID obscurity only',
            'reviewed' => false,
            'evidence_notes' => 'UUID alone is insufficient; non-owners can access documents if UUID is known.',
        ],
        [
            'id' => 'C4',
            'route_name' => 'secure.uuid.show',
            'resource' => 'Documents',
            'action' => 'Read',
            'object_reference' => 'UUID',
            'rule_enforcement_point' => 'DocumentPolicy@view',
            'reviewed' => true,
            'evidence_notes' => 'Policy check defends UUID route against IDOR attempts.',
        ],
        [
            'id' => 'C5',
            'route_name' => 'insecure.invoices.show',
            'resource' => 'Invoices',
            'action' => 'Read',
            'object_reference' => 'invoice_number',
            'rule_enforcement_point' => 'No policy or gate',
            'reviewed' => false,
            'evidence_notes' => 'Invoice number route leaks records across user accounts.',
        ],
        [
            'id' => 'C6',
            'route_name' => 'secure.invoices.show',
            'resource' => 'Invoices',
            'action' => 'Read',
            'object_reference' => 'invoice_number',
            'rule_enforcement_point' => 'InvoicePolicy@view',
            'reviewed' => true,
            'evidence_notes' => 'Invoice ownership validated in policy before response.',
        ],
        [
            'id' => 'C7',
            'route_name' => 'api.insecure.invoices.show',
            'resource' => 'Invoices',
            'action' => 'Read',
            'object_reference' => 'invoice_number',
            'rule_enforcement_point' => 'Auth only, no object-level policy',
            'reviewed' => false,
            'evidence_notes' => 'Authenticated non-owner can fetch another user invoice via API.',
        ],
        [
            'id' => 'C8',
            'route_name' => 'api.secure.invoices.show',
            'resource' => 'Invoices',
            'action' => 'Read',
            'object_reference' => 'invoice_number',
            'rule_enforcement_point' => 'InvoicePolicy@view',
            'reviewed' => true,
            'evidence_notes' => 'Sanctum auth plus policy ensures object-level authorization.',
        ],
    ],
];
